version: '2.1'

volumes:
  dag_data: {}
  postgres_data: {}
  
services:
  nginx:
    image: nginx:latest
    container_name: airflow_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - webserver

  git-sync:
    image: openweb/git-sync:0.0.1
    environment:
      GIT_SYNC_REPO: ${DAGS_REPO}
      GIT_SYNC_DEST: "/git"
      GIT_SYNC_BRANCH: ${DAGS_REPO_BRANCH:-master}
      GIT_SYNC_REV: "FETCH_HEAD"
      GIT_SYNC_WAIT: "10"
    volumes:
      - ./dags:/git
    restart: always

  redis:
    image: 'redis:5.0.5'
    command: redis-server --requirepass redispass
  
  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-airflow}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-airflow}
      - POSTGRES_DB=${POSTGRES_DB:-airflow}
      - PGDATA=${PGDATA:-/var/lib/postgresql/data/pgdata}
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
  
  webserver:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - postgres
      - redis
    environment:
      - EXECUTOR=Celery
      - LOAD_EX=${LOAD_EX:-n}
      - FERNET_KEY=${FERNET_KEY:-46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=}
      - POSTGRES_USER=${POSTGRES_USER:-airflow}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-airflow}
      - POSTGRES_DB=${POSTGRES_DB:-airflow}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispass}
      - AIRFLOW__CORE__DAGS_FOLDER=dags/dags
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-NotSet}  # Delete these if using hosts instance profile
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-NotSet}
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
      - ./requirements.txt:/requirements.txt
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3
  
  flower:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - redis
    environment:
      - EXECUTOR=Celery
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispass}
    ports:
      - "5555:5555"
    command: flower
  
  scheduler:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - webserver
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
      - ./requirements.txt:/requirements.txt
    environment:
      - EXECUTOR=Celery
      - LOAD_EX=${LOAD_EX:-n}
      - FERNET_KEY=${FERNET_KEY:-46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=}
      - POSTGRES_USER=${POSTGRES_USER:-airflow}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-airflow}
      - POSTGRES_DB=${POSTGRES_DB:-airflow}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispass}
      - AIRFLOW__CORE__DAGS_FOLDER=dags/dags
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-NotSet}  # Delete these if using hosts instance profile
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-NotSet}
    command: scheduler
  
  worker:
    image: puckel/docker-airflow:1.10.9
    restart: always
    depends_on:
      - scheduler
    volumes:
      - ./dags:/usr/local/airflow/dags
      - ./plugins:/usr/local/airflow/plugins
      - ./requirements.txt:/requirements.txt
    environment:
      - EXECUTOR=Celery
      - FERNET_KEY=${FERNET_KEY:-46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=}
      - POSTGRES_USER=${POSTGRES_USER:-airflow}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-airflow}
      - POSTGRES_DB=${POSTGRES_DB:-airflow}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redispass}
      - AIRFLOW__CORE__DAGS_FOLDER=dags/dags
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-NotSet}  # Delete these if using hosts instance profile
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-NotSet}
    command: worker
